spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: PAYMENT-A-SERVICE
          uri: lb://PAYMENT-A-SERVICE
          predicates:
            - Path=/savings/a/**

        - id: PAYMENT-B-SERVICE
          uri: lb://PAYMENT-B-SERVICE
          predicates:
            - Path=/savings/b/**

logging:
  file:
    name: C:\Users\VENKAT\PaymentModule\Api-Gateway\api-gateway.log

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

server:
  port: 8080
